Table Actuacion {
  id                int [pk, not null] // Identificador único de la actuación.
  codigo_amar_id    int [not null, ref: > Codigo_amar.id] // Identificador relacionado con un código amar.
  codigo_interno    varchar(50) // Código interno de la actuación.
  expediente_id     int [not null, ref: > Expediente.id] // Relación con el expediente.
  sede_id_registro  int [not null] // Sede donde se registra la actuación.
  archivo_id        int [ref: > Archivo.id] // Relación con un archivo asociado.
  coordinador_id    int [ref: > Persona.id] // Coordinador responsable.
  profesional_id    int [ref: > Persona.id] // Profesional responsable.
  actuacion_area_id int [not null, ref: > Actuacion_area.id] // Relación con el área de actuación.
  programa_id       int  // Relación con un programa asociado.
  acompanado        smallint // Indica si hubo acompañamiento (1: sí, 0: no).
  tipo_acompanante_id int  // Tipo de acompañante.
  acompanante_id    int [ref: > Persona.id] // Persona que acompaña.
  persona_id_creado int [not null, ref: > Persona.id] // Persona que creó el registro.
  persona_id_modificado int [ref: > Persona.id] // Persona que modificó el registro.
  persona_id_anulado int [ref: > Persona.id] // Persona que anuló el registro.
  numero_participante int // Número de participantes involucrados.
  grupal           smallint // Indica si la actuación es grupal (1: sí, 0: no).
  taller           smallint // Indica si es parte de un taller (1: sí, 0: no).
  objetivo         varchar(300) // Objetivo de la actuación.
  texto            text // Detalles o descripción de la actuación.
  observacion      text // Observaciones adicionales.
  confidencial     text // Información confidencial asociada.
  tipo_juridica    enum('ADMINISTRATIVA', 'PENAL') // Tipo de actuación jurídica.
  regularizado     smallint // Indica si está regularizado (1: sí, 0: no).
  voluntario_id    int [ref: > Persona.id] // Relación con un voluntario.
  lugar_deteccion_id int // Lugar de detección.
  fecha_ingreso    date // Fecha de ingreso de la actuación.
  fecha_creado     timestamp [default: `current_timestamp()`] // Fecha de creación.
  fecha_modificado timestamp  // Última modificación.
  fecha_anulado    timestamp // Fecha de anulación, si aplica.
  eliminado        tinyint [default: 0] // Indica si el registro fue eliminado (0: no, 1: sí).
}

Table Persona {
  id                    int [pk, not null]
  tipo_persona_id       int //[not null, ref: > Tipo_persona.id]
  tipo_identificacion_id int //[not null, ref: > Tipo_identificacion.id]
  municipio_id          int //[not null, ref: > Municipio.id]
  numero_identificacion varchar(200) [not null]
  nombre                varchar(200) [not null]
  apellidos             varchar(200) [not null]
  sexo                  enum('HOMBRE', 'MUJER')
  domicilio             varchar(300)
  codigo_postal         varchar(200)
  telefono              varchar(15)
  email                 varchar(300)
  eliminado             tinyint [default: 0]
}

Table Expediente {
  id                      int [pk, not null]
  persona_registro_id     int //[not null, ref: > Persona.id]
  entrevista_deteccion_id int //[ref: > Entrevista.id]
  entrevista_valoracion_id int //[ref: > Entrevista.id]
  codigo_amar_id          int //[not null, ref: > Codigo_amar.id]
  eliminado               tinyint [default: 0]
}

Table Actuacion_area {
  id                 int [pk, not null]
  area               enum('ATENCION_SOCIAL', 'EDUCATIVA', 'JURIDICA', 'OCIO_TIEMPO_LIBRE', 'PSICOLOGICA', 'RETORNO', 'SALUD', 'SANITARIA', 'SOCIOLABORAL', 'UNIDAD_MOVIL')
  tipo_actuacion_id  int //[not null, ref: > Tipo_actuacion.id]
  eliminado          tinyint [default: 0]
}

Table Codigo_amar {
  id             int [pk, not null]
  codigo         varchar(20) [not null]
  fecha_creado   timestamp [not null, default: `current_timestamp()`]
  eliminado      tinyint [default: 0]
}

Table Archivo_persona_registro {
  id                     int [pk, not null]
  persona_registro_id    int //[not null, ref: > Persona.id]
  tipo_archivo_id        int //[not null, ref: > Tipo_archivo.id]
  archivo_id             int //[not null, ref: > Archivo.id]
  descripcion            varchar(200)
  actuacion_id           int [ref: > Actuacion.id]
  amonestacion_id        int //[ref: > Amonestacion.id]
  retorno_voluntario_id  int //[ref: > Retorno_voluntario.id]
  fecha_caducado         date
  eliminado              tinyint [default: 0]
}

Table Archivo {
  id             int [pk, not null]
  nombre         varchar(200) [not null]
  nombre_temp    varchar(200) [not null]
  tamano_bytes   bigint [not null]
  mimetype       varchar(50)
  fecha_creado   timestamp [not null, default: `current_timestamp()`]
  eliminado      tinyint [default: 0]
}

